#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : chromebeta
Version  : 88.0.4324.96
Release  : 2
URL      : file:///insilications/build/clearlinux/packages/chromebeta/chromebeta-88.0.4324.96.tar.gz
Source0  : file:///insilications/build/clearlinux/packages/chromebeta/chromebeta-88.0.4324.96.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: chromebeta-bin = %{version}-%{release}
Requires: chromebeta-data = %{version}-%{release}
Requires: chromebeta-man = %{version}-%{release}
BuildRequires : bash
BuildRequires : buildreq-cmake
BuildRequires : ca-certs
BuildRequires : cpio-bin
BuildRequires : curl
BuildRequires : curl-bin
BuildRequires : curl-dev
BuildRequires : curl-lib
BuildRequires : findutils
BuildRequires : mlocate
BuildRequires : openssl-dev
BuildRequires : openssl-lib
BuildRequires : p11-kit
BuildRequires : pcre-dev
BuildRequires : pcre-extras
BuildRequires : rpm
BuildRequires : rpm-extras
BuildRequires : xmlstarlet
BuildRequires : zlib-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
# Disable automatic requeriments processing
AutoReq: no
# Disable automatic provides processing
AutoProv: no

%description
No detailed description available

%package bin
Summary: bin components for the chromebeta package.
Group: Binaries
Requires: chromebeta-data = %{version}-%{release}
# Disable automatic requeriments processing
AutoReq: no
# Disable automatic provides processing
AutoProv: no

%description bin
bin components for the chromebeta package.


%package data
Summary: data components for the chromebeta package.
Group: Data
# Disable automatic requeriments processing
AutoReq: no
# Disable automatic provides processing
AutoProv: no

%description data
data components for the chromebeta package.


%package man
Summary: man components for the chromebeta package.
Group: Default
# Disable automatic requeriments processing
AutoReq: no
# Disable automatic provides processing
AutoProv: no

%description man
man components for the chromebeta package.


%prep
%setup -q -c -n chromebeta-88.0.4324.96.tar
cd %{_builddir}/chromebeta-88.0.4324.96.tar

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1611498824
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=16 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=16 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=16 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=16 "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1611498824
rm -rf %{buildroot}
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)
/opt/google/chrome-beta/MEIPreload/manifest.json
/opt/google/chrome-beta/MEIPreload/preloaded_data.pb
/opt/google/chrome-beta/WidevineCdm/LICENSE
/opt/google/chrome-beta/WidevineCdm/_platform_specific/linux_x64/libwidevinecdm.so
/opt/google/chrome-beta/WidevineCdm/manifest.json
/opt/google/chrome-beta/chrome
/opt/google/chrome-beta/chrome-sandbox
/opt/google/chrome-beta/chrome_100_percent.pak
/opt/google/chrome-beta/chrome_200_percent.pak
/opt/google/chrome-beta/crashpad_handler
/opt/google/chrome-beta/default-app-block
/opt/google/chrome-beta/default_apps/docs.crx
/opt/google/chrome-beta/default_apps/drive.crx
/opt/google/chrome-beta/default_apps/external_extensions.json
/opt/google/chrome-beta/default_apps/gmail.crx
/opt/google/chrome-beta/default_apps/youtube.crx
/opt/google/chrome-beta/google-chrome
/opt/google/chrome-beta/google-chrome-beta
/opt/google/chrome-beta/icudtl.dat
/opt/google/chrome-beta/libEGL.so
/opt/google/chrome-beta/libGLESv2.so
/opt/google/chrome-beta/locales/am.pak
/opt/google/chrome-beta/locales/ar.pak
/opt/google/chrome-beta/locales/bg.pak
/opt/google/chrome-beta/locales/bn.pak
/opt/google/chrome-beta/locales/ca.pak
/opt/google/chrome-beta/locales/cs.pak
/opt/google/chrome-beta/locales/da.pak
/opt/google/chrome-beta/locales/de.pak
/opt/google/chrome-beta/locales/el.pak
/opt/google/chrome-beta/locales/en-GB.pak
/opt/google/chrome-beta/locales/en-US.pak
/opt/google/chrome-beta/locales/es-419.pak
/opt/google/chrome-beta/locales/es.pak
/opt/google/chrome-beta/locales/et.pak
/opt/google/chrome-beta/locales/fa.pak
/opt/google/chrome-beta/locales/fi.pak
/opt/google/chrome-beta/locales/fil.pak
/opt/google/chrome-beta/locales/fr.pak
/opt/google/chrome-beta/locales/gu.pak
/opt/google/chrome-beta/locales/he.pak
/opt/google/chrome-beta/locales/hi.pak
/opt/google/chrome-beta/locales/hr.pak
/opt/google/chrome-beta/locales/hu.pak
/opt/google/chrome-beta/locales/id.pak
/opt/google/chrome-beta/locales/it.pak
/opt/google/chrome-beta/locales/ja.pak
/opt/google/chrome-beta/locales/kn.pak
/opt/google/chrome-beta/locales/ko.pak
/opt/google/chrome-beta/locales/lt.pak
/opt/google/chrome-beta/locales/lv.pak
/opt/google/chrome-beta/locales/ml.pak
/opt/google/chrome-beta/locales/mr.pak
/opt/google/chrome-beta/locales/ms.pak
/opt/google/chrome-beta/locales/nb.pak
/opt/google/chrome-beta/locales/nl.pak
/opt/google/chrome-beta/locales/pl.pak
/opt/google/chrome-beta/locales/pt-BR.pak
/opt/google/chrome-beta/locales/pt-PT.pak
/opt/google/chrome-beta/locales/ro.pak
/opt/google/chrome-beta/locales/ru.pak
/opt/google/chrome-beta/locales/sk.pak
/opt/google/chrome-beta/locales/sl.pak
/opt/google/chrome-beta/locales/sr.pak
/opt/google/chrome-beta/locales/sv.pak
/opt/google/chrome-beta/locales/sw.pak
/opt/google/chrome-beta/locales/ta.pak
/opt/google/chrome-beta/locales/te.pak
/opt/google/chrome-beta/locales/th.pak
/opt/google/chrome-beta/locales/tr.pak
/opt/google/chrome-beta/locales/uk.pak
/opt/google/chrome-beta/locales/vi.pak
/opt/google/chrome-beta/locales/zh-CN.pak
/opt/google/chrome-beta/locales/zh-TW.pak
/opt/google/chrome-beta/nacl_helper
/opt/google/chrome-beta/nacl_helper_bootstrap
/opt/google/chrome-beta/nacl_irt_x86_64.nexe
/opt/google/chrome-beta/product_logo_128_beta.png
/opt/google/chrome-beta/product_logo_16_beta.png
/opt/google/chrome-beta/product_logo_24_beta.png
/opt/google/chrome-beta/product_logo_256_beta.png
/opt/google/chrome-beta/product_logo_32_beta.png
/opt/google/chrome-beta/product_logo_32_beta.xpm
/opt/google/chrome-beta/product_logo_48_beta.png
/opt/google/chrome-beta/product_logo_64_beta.png
/opt/google/chrome-beta/resources.pak
/opt/google/chrome-beta/swiftshader/libEGL.so
/opt/google/chrome-beta/swiftshader/libGLESv2.so
/opt/google/chrome-beta/v8_context_snapshot.bin
/opt/google/chrome-beta/xdg-mime
/opt/google/chrome-beta/xdg-settings

%files bin
%defattr(-,root,root,-)
/usr/bin/google-chrome-beta

%files data
%defattr(-,root,root,-)
/usr/share/appdata/google-chrome-beta.appdata.xml
/usr/share/applications/google-chrome-beta.desktop
/usr/share/gnome-control-center/default-apps/google-chrome-beta.xml

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/google-chrome-beta.1.gz
